### PR TITLE
Improve code

### PR DESCRIPTION
**Pull request by zdenop**
- improvement of python style
- improved docs
- drop support of outdated version of python and tesseract

### CODE REVIEW

**Comment by zdenop** [comment]
these are initial steps for automatic creating of windows packages (maybe other platforms too)

**Comment by zdenop** [comment]
any comments on this?

**Comment by sirfz** [comment]
What's the reason behind dropping 3.04 support?

**Comment by zdenop** [comment]
outdated, not maintained and not already several years unsupported version?

**Comment by sirfz** [comment]
True but it costs us nothing to keep supporting it just in case there are certain environments with an older tesseract version outside of the user's control (for example).

**Comment by zdenop** [comment]
IMO this would be very strange situation that user can use the latest python module but has to use old unsupported library (16 Feb 2016). BTW: why not 3.05.02 (released in 19 Jun 2018) that has a lot of fixes? 
Anyway it is up to you. Soon there will be version 5.

**Comment by sirfz** [comment]
I agree with you but, believe it or not, it's still possible to have such a situation. The fact that it doesn't affect our code-base at all makes it an unnecessary change for us and potentially an unnecessary inconvenience for some users, that's why I prefer not to make this change.

**Comment by zdenop** [comment]
As I wrote - it is up to you.  You can cherry-pick commits, or merge PR and then revert that one.

**Pull request closed without merging**
