### PR TITLE
Zdenop improve code

### PR DESCRIPTION
**Pull request by sirfz**

### CODE REVIEW

**Comment by bertsky** [comment]
@sirfz I welcome the progress and your active approach to @zdenop's work, but IMHO a few things went wrong here:
- squash instead of merge; that's especially problematic since 
   - it conflates the style changes in bb7ea64 with the functional changes elsewhere
   - your 7db96c9 is only a partial revert of bb7ea64 (style changes) and of dcb5996 (`.save` format)
- the partial revert of dcb5996 (`.save` format) still makes BMP the new default over PNG; I understand that reducing dependencies is worthwhile, but in this case, it comes with the price of (possibly) loosing quality: AFAICS the PNG could retain the DPI information and pass it on to Tesseract, which is impossible with BMP

**Comment by sirfz** [comment]
Hi @bertsky appreciate your input.

* There's been mixed use between single-quotes and double quotes for different reasons (different people committing code, copy-pasted code, etc). I personally don't think it's a problem but if we were to pick one, I choose single-quotes so I reverted the changes and made extra changes to my best effort.

* I'm not an image-format expert and from what I read my understanding was that BMP preserves quality so I figured it is a safe fallback (which is why I reverted the change to `image.format or 'BMP'` instead of just `'BMP'`). Of course this is open for debate and I'm all ears and happy to make any changes that provide the best solution.

**Comment by bertsky** [comment]
Thanks Fayez for explaining!

> * There's been mixed use between single-quotes and double quotes for different reasons (different people committing code, copy-pasted code, etc). I personally don't think it's a problem but if we were to pick one, I choose single-quotes so I reverted the changes and made extra changes to my best effort.

Understood, totally makes sense.

> * I'm not an image-format expert and from what I read my understanding was that BMP preserves quality so I figured it is a safe fallback (which is why I reverted the change to `image.format or 'BMP'` instead of just `'BMP'`). Of course this is open for debate and I'm all ears and happy to make any changes that provide the best solution.

Well there is still #207, so PNG might not be the best option for other reasons. Also, it's still possible to `SetVariable('user_defined_dpi', str(image.info['dpi']))` to preserve that information. I'm just worried about defaults and letting these things slip through. DPI is a very important datum for Tesseract's segmentation, and its internal heuristic for DPI estimation is extremely crude (it's basically a rule of thumb against the median line height).

Also, as I've just learned, it seems that BMP does have the capability of preserving pixel density information. There's a pixels per meter field in the DIB header, which [apparently](https://github.com/DanBloomberg/leptonica/blob/68d2cc15b955192f65772689d258a6d10dba52f5/src/bmpio.c#L185-L186) Leptonica's bmpio.c [understands](https://github.com/DanBloomberg/leptonica/blob/68d2cc15b955192f65772689d258a6d10dba52f5/src/bmpio.c#L275-L276), and (even more surprisingly) Pillow [fully supports](https://github.com/python-pillow/Pillow/blob/a72ae6823c3b44f9643cc53523e87fceaea157c9/src/PIL/BmpImagePlugin.py) since very long.

**Comment by bertsky** [comment]
Confirmed via OSD experiments: in osdetect, there is (unfortunately) no `user_dpi` override mechanism. Thus, if the image format does not convey pixel density metadata, then you're out of luck (and results will be much worse). As it stands (current master), with `PNG` as the intermediary (`SetImage` → `_image_buffer` → `Image.save(img.format)`), I do get:
```
Warning. Invalid resolution 0 dpi. Using 70 instead.
```

(Despite having good `img.info['resolution']` metadata.) However, as soon as I set `img.format = 'BMP'`, the warning goes away!

So considering the likely bug around libPNG, I am actually very happy with the current state. Thanks again, @zdenop!

**Comment by sirfz** [comment]
> As it stands (current master), with `PNG` as the intermediary (`SetImage` → `_image_buffer` → `Image.save(img.format)`), ...

Current master falls back to `BMP` (https://github.com/sirfz/tesserocr/blob/711cbab544dbb4bd3dcf1f13aad9d0fef20fcac7/tesserocr.pyx#L332)

**Pull request merged**
