### PR TITLE
Test 3.7 final and 3.8-dev on Travis and drop 3.3

### PR DESCRIPTION
**Pull request by johnthagen**

### CODE REVIEW

**Comment by johnthagen** [comment]
Python 3.3 failure appears to be related to the fact that `Pillow` no longer supports Python 3.3. Both 3.3 and 3.4 are end-of-life and not supported by `Pillow`. I would recommend dropping support for them.

https://pypi.org/project/Pillow/

Do the maintainers have a preference?

**Comment by sirfz** [comment]
I think it's safe for us to also drop support for Python 3.3, go ahead and disable it please.

**Comment by johnthagen** [comment]
@sirfz Would you like to keep 3.4? (It's also recently end-of-life).

**Comment by sirfz** [comment]
We can keep it for the time being as it's not broken (no harm)

**Comment by johnthagen** [comment]
@sirfz This PR should now be good to go.

**Pull request merged**
