### PR TITLE
fix BlockPolygon segfault (same as 052fb5d7d)

### LINKED ISSUE #150: pip install error (x86_64-linux-gnu-gcc) on ubuntu16.04
I am getting error when "Pip3 install tesserocr" on my ubuntu16.04 machine/

> pip3 install tesseractocr
> Collecting tesseractocr
>   Could not find a version that satisfies the requirement tesseractocr (from versions: )
> No matching distribution found for tesseractocr
> root@70d41ee0a519:/tmp# pip3 install tesserocr
> Collecting tesserocr
>   Downloading https://files.pythonhosted.org/packages/f8/6d/4e81e041f33a4419e59edcb1dbdf3c56e9393f60f5ef531381bd67a1339b/tesserocr-2.3.1.tar.gz (54kB)
>     100% |################################| 61kB 3.7MB/s
> Building wheels for collected packages: tesserocr
>   Running setup.py bdist_wheel for tesserocr ... error
>   Complete output from command /usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ocheer6s/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-3he8anm_ --python-tag cp34:
>   Supporting tesseract v3.04.01
>   Configs from pkg-config: {'libraries': ['lept', 'tesseract'], 'include_dirs': ['/usr/include'], 'cython_compile_time_env': {'TESSERACT_VERSION': 197633}}
>   running bdist_wheel
>   running build
>   running build_ext
>   building 'tesserocr' extension
>   creating build
>   creating build/temp.linux-x86_64-3.4
>   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.4m -c tesserocr.cpp -o build/temp.linux-x86_64-3.4/tesserocr.o
>   cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
>   tesserocr.cpp:38:20: fatal error: Python.h: No such file or directory
>   compilation terminated.
>   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 
>   ----------------------------------------
>   Failed building wheel for tesserocr
>   Running setup.py clean for tesserocr
> Failed to build tesserocr
> Installing collected packages: tesserocr
>   Running setup.py install for tesserocr ... error
>     Complete output from command /usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ocheer6s/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-avohldt9/install-record.txt --single-version-externally-managed --compile:
>     Supporting tesseract v3.04.01
>     Configs from pkg-config: {'cython_compile_time_env': {'TESSERACT_VERSION': 197633}, 'libraries': ['tesseract', 'lept'], 'include_dirs': ['/usr/include']}
>     running install
>     running build
>     running build_ext
>     building 'tesserocr' extension
>     creating build
>     creating build/temp.linux-x86_64-3.4
>     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.4m -c tesserocr.cpp -o build/temp.linux-x86_64-3.4/tesserocr.o
>     cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
>     tesserocr.cpp:38:20: fatal error: Python.h: No such file or directory
>     compilation terminated.
>     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 
>     ----------------------------------------
> Command "/usr/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ocheer6s/tesserocr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-avohldt9/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ocheer6s/tesserocr/

Here is my tesseract version

> tesseract 3.04.01
>  leptonica-1.73
>   libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.2

Any hints?

Thanks

### LINKED ISSUE #184: BlockPolygon crashes in Python 3 due to deallocation
Looks very much like #176

### PR DESCRIPTION
**Pull request by bertsky**
Fixes #184

I also ran tests with success.

### CODE REVIEW

**Comment by sirfz** [comment]
what's `ptaDestroy`? just leave `free` and the good should be good to merge

**Comment by bertsky** [comment]
`ptaDestroy` is the function from libleptonica (declared in allheaders.h) which is responsible for deinitializing the `Pta` pointer you receive from `BlockPolygon`. (I don't know if it does anything more than `free`.) From the documentation of the latter in Tesseract:
> Returns the polygon outline of the current block. The returned Pta must be ptaDestroy-ed after use.

I don't know why it does not compile in Travis. It compiled fine on my Ubuntu 18.04. Do you want me to investigate? (But I am afraid Travis debugging is not one of my strengths...)

**Comment by sirfz** [comment]
In that case you need to define `ptaDestroy` in [tesseract.pxd](https://github.com/sirfz/tesserocr/blob/master/tesseract.pxd). Just import it from the relevant header file with proper signature.

**Comment by bertsky** [comment]
Oh, I see. Thanks! I have updated the PR accordingly.

**Comment by bertsky** [comment]
Maybe I should also add a new test for `BlockPolygon`?

**Comment by bertsky** [comment]
BTW, do you plan to make another release before Tesseract 5? (I will very much depend on `BlockPolygon` [here](https://github.com/OCR-D/ocrd_tesserocr/blob/120fc75e5935fcfe1a82c6eddb08d3d60e04e8eb/ocrd_tesserocr/segment_region.py#L170).)

**Comment by wrznr** [comment]
> BTW, do you plan to make another release before Tesseract 5?

This would be much appreciated! Without the polygonal Regions, we often end up with results like
image
And nobody knows exactly when Tesseract 5 will ship...

**Comment by sirfz** [comment]
Yes a test for `BlockPolygon` would be much appreciated!

As for tesseract 5 support, please open a new issue (preferably with some of the new APIs and possible breaking/new changes).

**Comment by bertsky** [comment]
> Yes a test for `BlockPolygon` would be much appreciated!

Well, there are 2 problems: 

1. The tests never run on my installation, because I have more languages installed, and the [test](https://github.com/sirfz/tesserocr/blob/ae53f2e1e366a72db52866d1936539a4b8e537be/tests/test_api.py#L228) for `DetectOS` queries a position in the list of installed scripts. I tried to generalize this by looking into `tesserocr.get_languages()[1]` with that index, but it turns out the latter list is just [alphabetically sorted](https://github.com/tesseract-ocr/tesseract/blob/25534d325f908e284c39228c272da15d53800035/src/api/baseapi.cpp#L446), whereas the index looks in the [actual table](https://github.com/tesseract-ocr/tesseract/blob/25534d325f908e284c39228c272da15d53800035/src/api/baseapi.cpp#L1657). Thus, since it is impossible to test this reliably, I recommend _disabling_ that existing test for good.

2. There have not been any tests on layout analysis so far, except for trivial results that an empty image returns no components (in `test_empty_components` and `test_empty_small_components`). I guess we will have to reuse `eurotext.tif` and add tests for `GetComponentImages`, `AnalyseLayout.BoundingBox` _and_ `AnalyseLayout.BlockPolygon`. But small changes in the implementation could easily invalidate the exact pixel locations returned here. So how about testing pixel area very roughly?

**Comment by bertsky** [comment]
@sirfz, with your permission I will add a warning in the docstring of `DetectOS` that the index is useless in Python.

**Comment by bertsky** [comment]
Like so?

**Comment by sirfz** [comment]
Thank you :)

**Pull request merged**
