### PR TITLE
Migrate to tesseract 4.0.0 release

### PR DESCRIPTION
**Pull request by tysonite**
Related to #143

### CODE REVIEW

**Comment by tysonite** [comment]
Look like `test_detect_os` is flaky and depends on the environment. The result of running this test on my PC and TravisCI is different.

My PC:
```
FAIL: test_detect_os (tests.test_api.TestTessBaseApi)
Test DetectOS and DetectOrientationScript (tesseract v4+).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tysonite/tesserocr/tests/test_api.py", line 168, in test_detect_os
    self.assertEqual(orientation['script'], 1)
AssertionError: 2 != 1
```

Not sure how to fix that correctly.

TravisCI:
```
FAIL: test_detect_os (tests.test_api.TestTessBaseApi)
Test DetectOS and DetectOrientationScript (tesseract v4+).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/sirfz/tesserocr/tests/test_api.py", line 167, in test_detect_os
    self.assertEqual(orientation['orientation'], 0)
AssertionError: 3 != 0
```

**Comment by sirfz** [comment]
I think DetectOS is no longer supported in tesseract 4, I'll do some tests today and update the test cases accordingly.

**Comment by sirfz** [comment]
I tested the current master compiled against tesseract 4.0.0. Both Python2.7 and Python3.7 passed all tests with [tessdata](https://github.com/tesseract-ocr/tessdata) 3.04.00, 4.00 and 4.0.0.

I did an md5sum check on the `eng.traineddata` file bundled with the tesseract binary used in travis and noticed that it doesn't match any of the md5 hashes of `eng.traineddata` in either 3.04.00, 4.00 or 4.0.0. I suggest updating the archive with the 4.0.0 version from the tessdata repo and also include `osd.traineddata` which is currently missing.

**Comment by tysonite** [comment]
Thanks for suggestion. This works as expected now. I added `eng.traineddata` and `osd.traineddata` from `tessdata` repository and in both cases (my PC, Travis) tests are green.

Travis build of `tesserocr` depends on [tesseract-ocr-build](https://github.com/nijel/tesseract-ocr-build) project and it contains only [eng.traineddata](https://github.com/nijel/tesseract-ocr-build/blob/8c9df0e934aa8263922c4d41689a019c20b327c0/.travis.yml#L38) from `tessdata_fast` repository. Looks like there is some issue with data in `tessdata_fast` repository.

I've reverted changes in `test_init`. Let me know, please, if you would like me to change something else in this PR.

**Pull request merged**
